// Official Army exports supplied for regression testing on 2026-10-02.
export const armyCodeFixtures = [
  {
    sectoralId: 107,
    name: 'AStandardThomasList',
    groupSizes: [8, 7],
    code: 'axZrZXN0cmVsLWNvbG9uaWFsLWZvcmNlE0FTdGFuZGFyZFRob21hc0xpc3SBLAIBAQAIACEBBAAAABABAgAAAIOnAQIAAACHCwEJAAAAhyABBQAAACYBAQAAAIcNAQMAAACHUgEBAAACAQAHAIcXAQMAAACHEQEEAAAAEwEBAAAAhwwBAwAAAIcVAQIAAACHFQECAAAAhxUBBQAA',
  },
  {
    sectoralId: 1102,
    name: 'Tanuki are a mythological creature known for their huge discoballs',
    groupSizes: [9, 6],
    code: 'hE4Mc2hpbmRlbmJ1dGFpQlRhbnVraSBhcmUgYSBteXRob2xvZ2ljYWwgY3JlYXR1cmUga25vd24gZm9yIHRoZWlyIGh1Z2UgZGlzY29iYWxsc4EsAgEBAAkAhxsBBQAAAIcgAQIAAACHGwEDAAAAhxsBAQAAAIcfAQYAAACHHwEDAAAAhyMBAgAAAICiAQEAAACHKAEBAAACAQAGAICfAQIAAACHGwEDAAAAhyABAgAAAIcqAQEAAACHKQEBAAAAhyMBAgAA',
  },
  {
    sectoralId: 703,
    name: 'DropzoneCommander',
    groupSizes: [11, 6],
    code: 'gr8Kb3BlcmF0aW9ucxFEcm9wem9uZUNvbW1hbmRlcoEsAgEBAAsAglUEAQAAAIJVAQIAAACAwAEBAAAAh2sBAwAAAIO2AQIAAACCVAECAAAAh20BAgAAAIdvAQIAAACHcgEDAAAAh28CAQAAAIdvAgEAAAIBAAYAhJYBBAAAAG4BBAAAADEBAgAAAIYUAQYAAACCUQEBAAAAh2oBBQAA',
  },
  {
    sectoralId: 605,
    name: 'We Left Drakios at Home Again...',
    groupSizes: [10, 5],
    code: 'gl0JbmV4dC13YXZlIFdlIExlZnQgRHJha2lvcyBhdCBIb21lIEFnYWluLi4ugSwCAQEACgCHQwEBAAAAh0cBBgAAAIdfAQEAAACHXwEBAAAAhzoBBQAAAIIUAQEAAACCFAEBAAAAh1wBAQAAAIdeAQIAAACB%2FwEBAAACAQAFAIdEAQIAAACHVAEJAAAAh1QBCQAAAIdUAQkAAACHVAEJAAA%3D',
  },
  {
    sectoralId: 1102,
    name: '',
    groupSizes: [10, 5],
    code: 'hE4Mc2hpbmRlbmJ1dGFpASCBLAIBAQAKAIeSAQQAAQEkW3sidHlwZSI6InN0YXQiLCJzdGF0IjoiYnRzIiwicSI6Mn1dAIeSAgIAAQEmW3sidHlwZSI6InNraWxsIiwiaWQiOjI4LCJleHRyYSI6WzZdfV0Ah5IDAQABARtbeyJ0eXBlIjoic2tpbGwiLCJpZCI6MjEzfV0Ahx8BAQAAAIcfAQMAAACHHQEBAAAAhxoBAQAAAIcgAQMAAACHIAEBAAAAhykBAQAAAgEABQCHIwECAAAAhyMBAgAAAIciAQIAAACFNQECAAAAh1IBAQAA',
  },

];
